### ISSUE TITLE
Не атачится видео mp4 к репорту

### ISSUE THREAD

**Issue by rmarinsky** [allure-framework/allure-core#867] opened 2016-10-12 17:13 UTC
```
@Attachment(value = "VIDEO", type = "video/mp4")
    public byte[] attachVideo(File file) {
        try {
            return Files.toByteArray(file);
        } catch (IOException e) {
            e.printStackTrace();
            return new byte[0];
        }
    }
```
Версия allure-junit-adaptor 1.4.24.RC3

Пример видео:
https://yadi.sk/i/olMXp4wiwii8u

Есть аналогичный метод для прикрепления скриншота, так вот скриншот прикрепляется, но видео нет. При этом файл видео копируется в папку allure-report/data с сгенерированым новым наименованием, к примеру: cd751ce3-bdc4-45a0-bde3-2f810402075f-attachment.mp4 но в репорте с упавшим тестом не отображается.

Класс где использую соответствующий метод для аттача: [ссылка](https://github.com/rmarinsky/ElementObjectSelenide/blob/master/src/main/java/gsmserver/Utils/Report/CustomCollectors/AllureReportUtil.java)

Видео записано с помощью инструмента ffmpeg

**Comment by just-boris** [comment] 2016-10-12 17:27
duplicate of https://github.com/allure-framework/allure-core/issues/829?

**Comment by rmarinsky** [comment] 2016-10-12 17:38
@just-boris Not sure that it is dublicate for python. My example on java

**Comment by just-boris** [comment] 2016-10-12 17:47
@rmarinsky Basically I meant the link to tutorial that shows how to attach video
https://github.com/allure-framework/allure-core/issues/829#issuecomment-236552778

**Comment by rmarinsky** [comment] 2016-10-13 07:18
There is no tutorial 'how to attach video to allure report'. 
Example there is not help for me

**Comment by sskorol** [comment] 2016-10-13 07:26
@rmarinsky as far as I can see from your sources, you're calling attachment within `@AfterClass` method... correct me if I'm wrong, but I believe Allure may attach data for steps and test cases only... not for the entire class...

**Comment by rmarinsky** [comment] 2016-10-13 07:34
@sskorol allure may attach data for report also from testNG listerenrs or junit TestWatchers
I've tried before use method attachVideo() and from TestWatcher and from annotated @Test methods. Unfortunately video don't attach too. Video file .mp4 was located in allure-report/data folder, but wasn't attach to report :(

**Comment by rmarinsky** [comment] 2016-10-13 08:03
Exaple of report for reproduce with all needed files
https://yadi.sk/d/53RfaSeBwkVG2

**Comment by sskorol** [comment] 2016-10-13 08:32
@rmarinsky in testng you can't attach anything within configuration methods (like `Before / After`)... the only way, which worked for me, was using listeners for attachments... I can assume that junit might have some similar issue...

**Comment by rmarinsky** [comment] 2016-10-13 13:44
I don't understand.. Why hadn't been attaching video to report via TestWatcher before((( Actually I rewrite some and now video is attaching to report. Thanks guys and sorry for disturb
Example here: [link](https://github.com/rmarinsky/ElementObjectSelenide/tree/master/src/main/java/gsmserver/Utils/Report)

**Closed** 2016-10-22 12:23 UTC
