### ISSUE TITLE
Test counts doubled in "Behaviors" when feature is defined on the example group

### ISSUE THREAD

**Issue by aschlei** [allure-framework/allure-core#714] opened 2015-12-09 20:00 UTC
We're using Allure with Rspec, but having an issue where the test counts in Behaviors are being doubled.  This seems to be caused by defining the "feature" at the example group level.  To demonstrate, I started with this spec file:
```rb
require "rspec"
require "allure-rspec"
require "pathname"

RSpec.configure do |config|
  config.include AllureRSpec::Adaptor
end

AllureRSpec.configure do |config|
  config.output_dir = "allure_data"
  config.clean_dir  = true
end

feature = "My Feature"
describe "My Description" do

  it "should fail", feature: feature, story: "Story 1" do
    expect(1).to eq(2)
  end

  it "should pass", feature: feature, story: "Story 2" do
    expect(1).to eq(1)
  end

end
```
I ran this through rspec, then generated the report with allure, which generated the report I expected.  Xunit shows 1 passed test, 1 failed test; Behaviors shows 1 passed test, 1 failed test
![report1](https://cloud.githubusercontent.com/assets/14320686/11696831/f1ccb544-9e7b-11e5-99a3-e060ab33ff73.png)

I then modified my spec file to define the feature at the example group level (since it was the same for all examples)
```rb
feature = "My Feature"
describe "My Description", feature: feature do

  it "should fail", story: "Story 1" do
    expect(1).to eq(2)
  end

  it "should pass", story: "Story 2" do
    expect(1).to eq(1)
  end

end
```
When I generated the report, Xunit still shows 1 passed test, 1 failed test, but Behaviors shows 2 passed tests, 2 failed tests.
![report2](https://cloud.githubusercontent.com/assets/14320686/11696844/fd343efc-9e7b-11e5-9513-7dbb8510b132.png)

Versions:
Allure core 1.4.19
rspec 3.4
allure-rspec 0.7.5
allure-ruby-adaptor-api 0.6.9

We previously were using Allure 1.3.9 and didn't have this issue
![allure1 3 9](https://cloud.githubusercontent.com/assets/14320686/11696895/5967d652-9e7c-11e5-94bf-ae2797523bd9.png)

As a side note, I really liked how 1.3.9 showed the total story count for all features, and would love to get that back :)

**Comment by just-boris** [comment] 2015-12-09 21:29
Ok, please show what stories do you have on the behavior tab with latest Allure.

**Comment by aschlei** [comment] 2015-12-09 22:48
Here is the Behaviors tab with for my second report (with the feature defined on the example group):
![behaviors2](https://cloud.githubusercontent.com/assets/14320686/11701317/742662f2-9e94-11e5-805f-891d8fffc9ab.png)

**Comment by just-boris** [comment] 2015-12-09 22:51
Well, you got every test result twice.

We are storing some temporary files in the output directory. Are you sure that `allure_data` (according your config) was empty before the test run?

**Comment by aschlei** [comment] 2015-12-09 23:11
Yeah, allure_data is empty.  I tried it again just to be sure.  The Xunit tab is showing one result for each test; I would expect both tabs to have the problem if it wasn't getting cleared out (since I've seen that before when we weren't clearing our data :) ).  And our main test suite has the same problem: behaviors always shows twice as many tests as expected (if it was a problem with something not getting cleared, I would think this would keep increasing with each test run).

**Comment by just-boris** [comment] 2015-12-09 23:15
You have a good point. What do you have in the `*-testsuite.xml` file in the `allure_data` directory?

**Comment by aschlei** [comment] 2015-12-09 23:23
Here's the xml (minus the stack trace)
```xml
<?xml version="1.0"?>
<ns2:test-suite xmlns="" xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1449702303438" stop="1449702303459">
  <name>My Description</name>
  <title>My Description</title>
  <test-cases>
    <test-case start="1449702303439" stop="1449702303457" status="failed">
      <name>My Description should fail</name>
      <title>My Description should fail</title>
      <failure>
        <message>
expected: 2
     got: 1

(compared using ==)
</message>
        <stack-trace>...</stack-trace>
      </failure>
      <steps/>
      <attachments/>
      <labels>
        <label name="feature" value="My Feature"/>
        <label name="thread" value="15656076"/>
        <label name="host" value="ASCHLEI1"/>
        <label name="story" value="Story 1"/>
      </labels>
      <parameters/>
    </test-case>
    <test-case start="1449702303458" stop="1449702303458" status="passed">
      <name>My Description should pass</name>
      <title>My Description should pass</title>
      <steps/>
      <attachments/>
      <labels>
        <label name="feature" value="My Feature"/>
        <label name="thread" value="15656076"/>
        <label name="host" value="ASCHLEI1"/>
        <label name="story" value="Story 2"/>
      </labels>
      <parameters/>
    </test-case>
  </test-cases>
  <labels>
    <label name="feature" value="My Feature"/>
    <label name="thread" value="15656076"/>
    <label name="host" value="ASCHLEI1"/>
  </labels>
</ns2:test-suite>
```

**Comment by just-boris** [comment] 2015-12-10 09:21
Ok, the resulting xml is wrong. So that is an issue in RSpec adaptor.

@allure-framework/ruby-developers what do you think about it? Now the `feature` label is put twice and it causes issues.

**Comment by smecsia** [comment] 2015-12-10 11:40
@just-boris what do you mean by `is put twice`? AFAIU xml is correct. We have one `feature` label for test-suite and the same for each test-case.

**Comment by smecsia** [comment] 2015-12-10 11:55
Summon @baev. I suppose this is a bug in generator.  In any case, even if this behavior was changed intentionally to break the backward compatibility (which supposes that `feature` is not inherited anymore), the result of generation is strange. Why is it duplicating cases?

**Comment by dw512** [comment] 2016-02-05 03:14
I have the same problems in my allure behavior report, but if you remove the ":feature=>"xxx'' “ from the describe module, then run again ,the report shows right, i don't know why , can any body help me?
maybe this is a bug in allure-rspec test report.

**Comment by smecsia** [comment] 2016-02-05 10:35
@dw512 This is a debatable topic. The problem is related to the changed behavior of allure generator in newer versions. It duplicates all the test cases when `testSuite` and `testcase` elements have the same meta attributes. I believe this is a bug which should be fixed, but we're waiting for @baev .

**Comment by baev** [comment] 2016-02-05 12:09
I'll release the fix in few days

**Closed** 2016-02-05 12:08 UTC
Labels: bug
