### ISSUE TITLE
Report dublication

### ISSUE THREAD

**Issue by pozharko** [allure-framework/allure-core#491] opened 2015-02-17 07:15 UTC
Sometimes reports are shown in a wrong way - looks like there are two reports, and one of them is scrollable, and another one is static. We use TestNG, report is created by Jenkins plugin v 2.5.
![screenshot from 2015-02-17 10 07 38](https://cloud.githubusercontent.com/assets/2892316/6224459/373e04b6-b68d-11e4-8242-22d9a825178e.png)
and after scrolling:
![screenshot from 2015-02-17 10 10 48](https://cloud.githubusercontent.com/assets/2892316/6224464/4870912c-b68d-11e4-9cb0-8742f0933904.png)

**Comment by just-boris** [comment] 2015-02-17 08:08
looks like https://github.com/allure-framework/allure-core/issues/410
What version of Allure are you using?

**Comment by pozharko** [comment] 2015-02-17 08:42
1.4.7

**Comment by pozharko** [comment] 2015-02-17 08:45
Also I use Google Chrome Version 40.0.2214.111 (64-bit), and refreshing the page fixes the problem.

**Comment by vania-pooh** [comment] 2015-02-17 08:52
@pozharko btw, 1.4.7 is marked as a pre-release because we found some issues with HTML layout there. So please fall back to 1.4.6. Version 1.4.8 with fixes will come soon.

**Comment by pozharko** [comment] 2015-02-17 09:12
Oh, thank you.

**Comment by pozharko** [comment] 2015-02-20 10:55
1.4.8 did not correct the problem

**Comment by just-boris** [comment] 2015-02-20 11:01
:(
we cannot reproduce, on available my computers and chromes it works good.
@pozharko what operating system and video card do you have?

**Comment by pozharko** [comment] 2015-02-20 11:45
Ubuntu 14.04
NVIDIA Corporation GF119 [GeForce GT 610]

**Comment by pozharko** [comment] 2015-02-20 11:51
May be problems are with report? I have report, where I can reproduce it.
This problem occur, when I click on different test-suites/test-cases and then click on failed test-case. Also @beforeClass method failed there.
Btw, Before/AfterClass methods are sometimes shown in a wrong way - I saw AfterClass step in the beggining of the next test.

**Comment by pozharko** [comment] 2015-03-26 11:55
no problems in version 1.4.10

**Closed** 2015-03-26 11:54 UTC
Labels: bug, face only
