### ISSUE TITLE
Title overrides parametrized part of testcase name

### ISSUE THREAD

**Issue by borislubimov** [allure-framework/allure-core#634] opened 2015-07-28 12:12 UTC
In parametrized test name of testcase consist of two parts test method name and name from Parameters annotations: testmethodname[Parameters name]
But with Title annotation title overrides whole testcase name not only test method name. This isn't right.
See https://yadi.sk/i/ngXOGApJi8iVx

**Comment by baev** [comment] 2015-09-01 17:53
@borislubimov sorry for the delay and thanks for suggestion. 

The problem is JUnit is not providing parameters for the test, it is only provides name of the test (which includes the parameters) depends on test runner you are using. So there is no clear way to add ability to use parameters in `@Title` (an example `@Title("Test (param1: {0}, param2: {1})")`)

**Comment by baev** [comment] 2016-06-24 15:58
Should be fixed in JUnit 5 (there is no such adaptor yet, but JUnit has its own `@DisplayName` annotation and better support of test parameters)

**Closed by baev** 2016-06-24 15:58 UTC
Labels: question
